<?php

namespace proxies\__CG__\entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonInfo extends \entities\PersonInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'id', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'last_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'first_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_phone', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_mail', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'phone', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'mail', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'adress', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'birth_date', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'matricule', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'blood_group', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'picture', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'create_date', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'gender', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'birth_city', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'nationality', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'old_school', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'state', 'version'];
        }

        return ['__isInitialized__', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'id', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'last_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'first_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_name', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_phone', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'guardian_mail', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'phone', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'mail', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'adress', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'birth_date', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'matricule', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'blood_group', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'picture', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'create_date', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'gender', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'birth_city', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'nationality', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'old_school', '' . "\0" . 'entities\\PersonInfo' . "\0" . 'state', 'version'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PersonInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLast_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLast_name', []);

        return parent::getLast_name();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirst_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirst_name', []);

        return parent::getFirst_name();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuardian_name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuardian_name', []);

        return parent::getGuardian_name();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuardian_phone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuardian_phone', []);

        return parent::getGuardian_phone();
    }

    /**
     * {@inheritDoc}
     */
    public function getGuardian_mail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuardian_mail', []);

        return parent::getGuardian_mail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirth_date()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirth_date', []);

        return parent::getBirth_date();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlood_group()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlood_group', []);

        return parent::getBlood_group();
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreate_date()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreate_date', []);

        return parent::getCreate_date();
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirth_city()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirth_city', []);

        return parent::getBirth_city();
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function getOld_school()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOld_school', []);

        return parent::getOld_school();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setLast_name($last_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLast_name', [$last_name]);

        return parent::setLast_name($last_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirst_name($first_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirst_name', [$first_name]);

        return parent::setFirst_name($first_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setGuardian_name($guardian_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuardian_name', [$guardian_name]);

        return parent::setGuardian_name($guardian_name);
    }

    /**
     * {@inheritDoc}
     */
    public function setGuardian_phone($guardian_phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuardian_phone', [$guardian_phone]);

        return parent::setGuardian_phone($guardian_phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setGuardian_mail($guardian_mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuardian_mail', [$guardian_mail]);

        return parent::setGuardian_mail($guardian_mail);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress($adress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirth_date($birth_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirth_date', [$birth_date]);

        return parent::setBirth_date($birth_date);
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function setBlood_group($blood_group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlood_group', [$blood_group]);

        return parent::setBlood_group($blood_group);
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreate_date($create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreate_date', [$create_date]);

        return parent::setCreate_date($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirth_city($birth_city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirth_city', [$birth_city]);

        return parent::setBirth_city($birth_city);
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality($nationality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function setOld_school($old_school)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOld_school', [$old_school]);

        return parent::setOld_school($old_school);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function __serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__serialize', []);

        return parent::__serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function __unserialize(array $serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unserialize', [$serialized]);

        return parent::__unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize(string $serialized): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptionId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptionId', [$id]);

        return parent::encryptionId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function decryptionId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decryptionId', [$id]);

        return parent::decryptionId($id);
    }

}
