<?php

namespace proxies\__CG__\entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscription extends \entities\Inscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'entities\\Inscription' . "\0" . 'id', '' . "\0" . 'entities\\Inscription' . "\0" . 'amount_paid', '' . "\0" . 'entities\\Inscription' . "\0" . 'rest_to_paid', '' . "\0" . 'entities\\Inscription' . "\0" . 'payment_date', '' . "\0" . 'entities\\Inscription' . "\0" . 'state', '' . "\0" . 'entities\\Inscription' . "\0" . 'candidat', '' . "\0" . 'entities\\Inscription' . "\0" . 'registrations', '' . "\0" . 'entities\\Inscription' . "\0" . 'fee', 'version'];
        }

        return ['__isInitialized__', '' . "\0" . 'entities\\Inscription' . "\0" . 'id', '' . "\0" . 'entities\\Inscription' . "\0" . 'amount_paid', '' . "\0" . 'entities\\Inscription' . "\0" . 'rest_to_paid', '' . "\0" . 'entities\\Inscription' . "\0" . 'payment_date', '' . "\0" . 'entities\\Inscription' . "\0" . 'state', '' . "\0" . 'entities\\Inscription' . "\0" . 'candidat', '' . "\0" . 'entities\\Inscription' . "\0" . 'registrations', '' . "\0" . 'entities\\Inscription' . "\0" . 'fee', 'version'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount_paid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount_paid', []);

        return parent::getAmount_paid();
    }

    /**
     * {@inheritDoc}
     */
    public function getRest_to_paid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRest_to_paid', []);

        return parent::getRest_to_paid();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayment_date()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayment_date', []);

        return parent::getPayment_date();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidat', []);

        return parent::getCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrations', []);

        return parent::getRegistrations();
    }

    /**
     * {@inheritDoc}
     */
    public function getFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFee', []);

        return parent::getFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount_paid($amount_paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount_paid', [$amount_paid]);

        return parent::setAmount_paid($amount_paid);
    }

    /**
     * {@inheritDoc}
     */
    public function setRest_to_paid($rest_to_paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRest_to_paid', [$rest_to_paid]);

        return parent::setRest_to_paid($rest_to_paid);
    }

    /**
     * {@inheritDoc}
     */
    public function setPayment_date($payment_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayment_date', [$payment_date]);

        return parent::setPayment_date($payment_date);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidat($candidat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidat', [$candidat]);

        return parent::setCandidat($candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function setFee($fee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFee', [$fee]);

        return parent::setFee($fee);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrations($registrations): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrations', [$registrations]);

        parent::setRegistrations($registrations);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function __serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__serialize', []);

        return parent::__serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function __unserialize(array $serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__unserialize', [$serialized]);

        return parent::__unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize(string $serialized): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptionId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptionId', [$id]);

        return parent::encryptionId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function decryptionId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decryptionId', [$id]);

        return parent::decryptionId($id);
    }

}
