<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//registration
$config['registrationform'] = array(
    //form fields
    "registrationformname" => "registrationform",
    "addregistration" => "addregistration",
    "lastname" => "lastname",
    "firstname" => "firstname",
    "guardianname" => "guardianname",
    "guardianphone" => "guardianphone",
    "guardianmail" => "guardianmail",
    "adress" => "adress",
    "birthdate" => "birthdate",
    "bloodgroup" => "bloodgroup",
    "birthcity" => "birthcity",
    "gender" => "gender",
    "maritalstatus" => "maritalstatus",
    "nationality" => "nationality",
    "phone" => "phone",
    "email" => "email",
    "oldschool" => "oldschool",
    "picture" => "picture",
    "pictureimg" => "img[]",
    "picturefile" => "file",
    "candidats" => "candidats",
    //form and table labels
    "num" => "N°",
    "lastnamelabel" => "Nom",
    "firstnamelabel" => "Prénoms",
    "matriculelabel" => "Numero matricule",
    "guardiannamelabel" => "Nom tuteur",  
    "guardianphonelabel" => "Numero tuteur",
    "guardianmaillabel" => "E-Mail tuteur",
    "adresslabel" => "Adresse",
    "birthdatelabel" => "Date naissance",
    "bloodgrouplabel" => "Group sanguin",
    "birthcitylabel" => "Ville naissance",
    "genderlabel" => "Sexe",
    "maritalstatuslabel" => "Situation matrimoniale",
    "nationalitylabel" => "Nationalité",
    "phonelabel" => "Téléphone",
    "emaillabel" => "Email",
    "oldschoollabel" => "Ecole de provenance",
    "picturelabel" => "Photo",
    "candidatslabel" => "Candidats",
    //form descriptions
    "lastnamedesc" => "le noms de l'aprenant",
    "firstnamedesc" => "le prénoms de l'aprenant",
    "guardiannamedesc" => "le nom du tuteur",
    "guardianphonedesc" => "le numero du tuteur",
    "guardianmaildesc" => "le mail du tuteur",
    "adressdesc" => "l'adresse",
    "birthdatedesc" => "Date de Naissance",
    "bloodgroupdesc" => "Group Sanguin",
    "birthcitydesc" => "la ville de naissance",
    "genderdesc" => "le sexe",
    "maritalstatusdesc" => "la situation matrimoniale",
    "maritalstatuslabel" => "Situation matrimoniale",
    "nationalitydesc" => "choisir la nationalité",
    "phonedesc" => "le numéro de téléphone",
    "emaildesc" => "l'adresse électronique",
    "oldschooldesc" => "Choisir l'établissement de provenance",
    "picturedesc" => "Choisir la photo",
    //form ids
    "lastnameid" => "lastnameid",
    "firstnameid" => "firstnameid" ,
    "guardiannameid" => "guardiannameid",
    "guardianphoneid" => "guardianphoneid",
    "guardianmailid" => "guardianmailid",
    "adressid" => "adressid",
    "birthdateid" => "birthdateid",
    "bloodgroupid" => "bloodgroupid",
    "birthcityid" => "birthcityid",
    "genderid" => "genderid",
    "maritalstatusid" => "maritalstatusid",
    "nationalityid" => "nationalityid",
    "phoneid" => "phoneid",
    "emailid" => "emailid",
    "oldschoolid" => "oldschoolid",
    "pictureid" => "pictureid",
    //table links
    "list" => "RegistrationController/registrationlist",
    "registrationeditedlink" => "RegistrationController/edit_registration",
    "registrationdeletedlink" => "RegistrationController/delete_registration",
    "registrationdetailslink" => "RegistrationController/registration_details"
);
